import { StyleSheet } from 'react-native';

export const dayCardStyles = StyleSheet.create({
  smartFlagMore: {
    minHeight: 28,
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d7e1ea',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  smartFlagMoreText: {
    color: '#425466',
    fontSize: 11,
    fontWeight: '900',
  },
  collapsiblePanel: {
    gap: 8,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ebe7df',
    backgroundColor: '#fffefa',
    padding: 12,
  },
  collapsibleHeader: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  timelineHeader: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#ebe7df',
    paddingTop: 12,
  },
  timeRailCompact: {
    width: 58,
    alignItems: 'center',
    gap: 8,
  },
  stopCompactBody: {
    flex: 1,
    gap: 8,
    minWidth: 0,
  },
  stopMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  stopTitleBlock: {
    flex: 1,
    minWidth: 180,
    gap: 5,
  },
  stopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  missingChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  missingChip: {
    color: '#5f5142',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e8d5a5',
    backgroundColor: '#fff9eb',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  stopRightRail: {
    minWidth: 104,
    maxWidth: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    gap: 8,
    flexWrap: 'wrap',
  },
  stopCompactActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
  },
  coordinateReadyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  stopNotePreview: {
    color: '#425466',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  stopDetailsGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#ebe7df',
    paddingTop: 10,
  },
  stopMenuWrap: {
    position: 'relative',
    alignItems: 'flex-end',
  },
  iconMenuButton: {
    minWidth: 54,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d7e8df',
    backgroundColor: '#f3fbf8',
  },
  iconMenuText: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '900',
  },
  stopMenuPanel: {
    position: 'absolute',
    top: 40,
    right: 0,
    zIndex: 10,
    width: 220,
    gap: 6,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d7e1ea',
    backgroundColor: '#ffffff',
    padding: 8,
    shadowColor: '#0a2540',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  stopMenuItem: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#f6f9fc',
    paddingHorizontal: 10,
  },
  stopMovePanel: {
    gap: 6,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    paddingTop: 4,
  },
  stopMenuDangerItem: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#ef4444',
    paddingHorizontal: 10,
  },
  deleteConfirmPanel: {
    gap: 8,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#fecdd3',
    backgroundColor: '#fff1f2',
    padding: 10,
  },
  inlineDisplayField: {
    minHeight: 24,
    justifyContent: 'center',
    borderRadius: 6,
  },
  inlineDisplayLabel: {
    color: '#425466',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  inlineDisplayValue: {
    color: '#0a2540',
    fontSize: 13,
    fontWeight: '800',
  },
  inlineTitleField: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  inlineMetaField: {
    flexShrink: 1,
    minWidth: 90,
  },
  inlineBadgeField: {
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d7e8df',
    backgroundColor: '#f3fbf8',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  inlineBadgeText: {
    color: '#0f766e',
    fontSize: 11,
    fontWeight: '900',
  },
  inlineTimeField: {
    alignItems: 'center',
    minWidth: 50,
  },
  inlineCostField: {
    minWidth: 74,
    alignItems: 'flex-end',
  },
  inlineCostText: {
    color: '#0a2540',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  inlineDetailField: {
    minWidth: 132,
    flexGrow: 1,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d8e5f2',
    backgroundColor: '#f7fbff',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineDetailFieldWide: {
    minWidth: 220,
    flexGrow: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#d8e5f2',
    backgroundColor: '#f7fbff',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
});
