import type { CurrencyCode } from '@/models';

export type TripRow = {
  id: string;
  owner_id: string;
  name: string;
  description: string | null;
  base_currency: CurrencyCode;
  starts_at: string | null;
  ends_at: string | null;
  home_location: unknown | null;
  settings: Record<string, unknown>;
  version: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type ItineraryNodeRow = {
  id: string;
  trip_id: string;
  poi_id: string | null;
  created_by: string;
  updated_by: string | null;
  type: string;
  title: string;
  notes: string | null;
  starts_at: string | null;
  ends_at: string | null;
  timezone: string | null;
  location: unknown | null;
  sort_order: number;
  transport_mode: string | null;
  route_to_next: Record<string, unknown> | null;
  reservation: Record<string, unknown>;
  equipment: unknown[];
  facilities: Record<string, boolean | string | number>;
  metadata: Record<string, unknown>;
  version: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type ExpenseRow = {
  id: string;
  trip_id: string;
  itinerary_node_id: string | null;
  paid_by: string;
  category: string;
  description: string;
  amount: number;
  currency: CurrencyCode;
  fx_rate_to_base: number | null;
  base_amount: number | null;
  occurred_at: string;
  split: Record<string, number>;
  receipt_url: string | null;
  metadata: Record<string, unknown>;
  version: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type TripExploreItemRow = {
  id: string;
  trip_id: string;
  created_by: string;
  item_type: 'note' | 'place' | 'section';
  title: string;
  description: string | null;
  category: string | null;
  place_name: string | null;
  formatted_address: string | null;
  latitude: number | null;
  longitude: number | null;
  google_place_id: string | null;
  google_maps_url: string | null;
  google_rating: number | null;
  google_primary_type: string | null;
  photo_name: string | null;
  photo_reference: string | null;
  photo_url: string | null;
  photo_attributions: unknown[];
  image_source: 'google_place_photo' | 'placeholder' | 'manual';
  sort_order: number;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};
